### ISSUE TITLE
Invaild Argument 2 

### ISSUE THREAD

**Issue by yijueli** [ni/grpc-labview#173] opened 2022-10-20 12:52 UTC
Version: v 0.5.0.2
Running environment: Linux RT

Steps to reproduce:
1. Pkill lvrt and close all the projects each time;(the KEY step!!! l guess that can make deployment last long enough.)
2. Open the helloworld.lvproj and run the Run Service.vi and then gRPC Client Test.vi. l added logic in the Start Sync.vi and gRPC Client Test.vi. You can download the code below.
3. Open the Big Project.lvproj and switch RUN.vi to the helloworld.lvproj and run it.

During the deployment of Big Project.lvproj, you could see the error from the helloworld.lvproj
![image](https://user-images.githubusercontent.com/105094769/196945126-5fda3628-3725-4bea-8375-ca701f17bca7.png)

Code(attached below): 
1.A big project consisting of just 5 copies of  the helloworld example. There was no logic in this project and it must be big enough to make deployment last long enough.
2. A helloworld project. In this project, the key code that must be added in the Start Sync.vi: **_List Folder.vi_** or some _**VI property nodes**_ like VI Path
![image](https://user-images.githubusercontent.com/105094769/196944133-c19e65b9-8910-4260-9e12-28f44ae9967f.png)
[error.zip](https://github.com/ni/grpc-labview/files/9830325/error.zip)

Had no idea about this issue. l saw this issue in many cases during our use but only could reproduce it in this way now.
After the error occured, the grpc services could still work in some cases and could not work in other cases.

**Comment by shivaprasad-basavaraj** [comment] 2022-10-31 10:33
@yijueli In the steps to reproduce can you clarify on what step 3 means? When you say "switch RUN.vi to helloworld.lvproj" Do you mean change the code in RUN.vi to use the server and client lvlib that is part of the helloworld.lvproj which you asked me to run first? 

Since these are two different lvproj I am assuming you ran the helloworld.lvproj in Step 2 disconnected it from the RT target and then ran "Big Project.lvproj". Is that correct?

Also when I look at the RUN.vi I see that there are two different Run Server calls as seen in the image below.

![image](https://user-images.githubusercontent.com/35128660/198987493-a1683a39-f02b-4965-9240-d69b0d60155b.png)

Is this what you had in your test VI as well? We allow only one grpc server to run on a machine at any given time. That might the source of your bug if you can reproduce it only with the additional code you added to include a "List Folder.vi". This might be making sure that a server is running long enough to force creation of another server in parallel which is not allowed.

**Comment by yijueli** [comment] 2022-10-31 12:40
@shivaprasad-basavaraj 
> In the steps to reproduce can you clarify on what step 3 means? When you say "switch RUN.vi to helloworld.lvproj" Do you mean change the code in RUN.vi to use the server and client lvlib that is part of the helloworld.lvproj which you asked me to run first?
> 
> Since these are two different lvproj I am assuming you ran the helloworld.lvproj in Step 2 disconnected it from the RT target and then ran "Big Project.lvproj". Is that correct?
![image](https://user-images.githubusercontent.com/105094769/199009602-53a324a8-7f05-4e2e-9e96-58d6d5775d98.png)
"switch RUN.vi to helloworld.lvproj" means the operation like the picture above. You can dynamically switch Run.vi to the helloworld.lvproj when the VIs in the helloworld.lvproj are running.

**Comment by yijueli** [comment] 2022-10-31 12:50
@shivaprasad-basavaraj 
> Also when I look at the RUN.vi I see that there are two different Run Server calls as seen in the image below.
> Is this what you had in your test VI as well? We allow only one grpc server to run on a machine at any given time.

You can delete the VIs you highlight. The error still exists.

**Comment by shivaprasad-basavaraj** [comment] 2022-11-04 10:30
@yijueli Debugging this bug I found that the issue was the timeout you had wired in the client test vi (image below). When we are deploying a large project to the RT target there would be delays in the server code processing the request leading to a timeout. If you wire an error out to the unary call as in the diagram below you can see that there is a deadline exceeded exception on the client side. If I remove the timeout on the client side I don't see the error anymore.

![image](https://user-images.githubusercontent.com/35128660/199951185-f9365ad4-d677-4413-b87f-7f1ddf905928.png)

The error on the server side is confusing and it should have said that the operation was canceled instead of giving out a generic invalid argument error. I will fix the error reporting for this issue.

**Comment by yijueli** [comment] 2022-11-04 12:57
@shivaprasad-basavaraj Thanks for the detailed explanation. l tested and Error -1004 from the client actually occurred earlier than Error -2 from the server. But one more question: does Error -1004 always infer that a client request is canceled? In fact,  when the client returns Error -1004, the server doesn't always return Error -2.

**Comment by shivaprasad-basavaraj** [comment] 2022-11-07 05:57
> does Error -1004 always infer that a client request will be canceled? In fact, when the client returns Error -1004, the server doesn't always return Error -2.

You might not always get an error on the server. It depends on what state the server was in when the timeout happened. It might be that the server had finished processing the request and sent a reply but the client timed out before it could receive the response.

**Comment by shivaprasad-basavaraj** [comment] 2022-11-07 05:59
The error code has been fixed in PR #184

**Closed by shivaprasad-basavaraj** 2022-11-07 05:59 UTC
Labels: type: showstopper
