### ISSUE TITLE
CompleteMetadataRegistration.vi is hanging during the Client creation process if there are empty messages in the proto

### ISSUE THREAD

**Issue by arevh** [ni/grpc-labview#275] opened 2023-07-18 06:34 UTC
CompleteMetadataRegistration.vi is hanging during the Client creation process if there are empty messages in the proto, e.g. message Sensor{}.

AB#2458342

**Comment by yash-ni** [comment] 2023-08-07 12:27
Couldn't reproduce this bug in grpc-labview v1.0.0.5, hence closing this issue.

**Closed by yash-ni** 2023-08-07 12:27 UTC
Labels: type: bug, type: showstopper
