### ISSUE TITLE
Labview crashes when two (or more) servers are stopped

### ISSUE THREAD

**Issue by HouetIBS** [ni/grpc-labview#356] opened 2024-03-22 08:49 UTC
I'm using two servers and two clients in one application. When running the servers and clients, this works really well.

When I close one server (no matter which one I choose), the server is closed nicely as well.
But, when I close the second server, Labview crashes when calling the LVStopServer in the dll.
![image](https://github.com/ni/grpc-labview/assets/164482238/6c8280c7-b7a4-418f-a46e-4ff954ded35d)
(The gRPCid server is for both servers not 0 and unique for all servers)

If I just use the simple 'helloworld'-example and just copy an extra server in the application, it is really easy to reproduce the problem.
![image](https://github.com/ni/grpc-labview/assets/164482238/29f5ec85-2858-4c49-8fa6-70bd638479cc)

Would be great if this can be fixed.

Thanks in advance.

PS:
- Used LabVIEW 2021 32 and 64bit to verify this.
- Used gRPC-LabVIEW 1.2.0.1

With kind regards,

Erik

AB#2689710

**Comment by nischalks** [comment] 2024-04-04 12:31
Hi @HouetIBS, we wanted to check with you, which NI product team do you belong to ?

**Comment by HouetIBS** [comment] 2024-04-04 12:35
Hi,

I do not really understand your question. I work for IBS Precision Engineering in the Netherlands.
We use Labview for pretty much every application we build.

The current application, which uses gRPC, is written in Labview 2021 64bit.

I really like the gRPC/proto implementation to use as a communication standard between software products. Good that you all started a gRPC implementation for Labview.
Unfortunate, there are some challenges to overtake to make it a really good experience.

Met vriendelijke groeten,

Erik Houet
IBS Precision Engineering B.V.

**Comment by nischalks** [comment] 2024-04-05 10:32
Thats nice to know. Thanks Erik!

**Comment by gmkrtchy** [comment] 2024-05-27 09:46
Hi @nischalks,

For one of our Key Customer project we are using LV gRPC.
I faced the same issue, stopping two parallel running Servers caused LV Crash.
The same issue happened also on LabVIEW RT.
Any updates about the status of this issue? 
Thank you in advance.

Gor Mkrtchyan
Senior Solutions Engineer | CCS EMEA

**Comment by SallyTYT** [comment] 2024-05-31 06:21
Not sure if you are facing the same issue as this one https://github.com/ni/grpc-labview/issues/279

**Comment by gmkrtchy** [comment] 2024-05-31 08:09
@SallyTYT thanks for the comment,

My case is little bit different, I could properly get data from both clients, the problem is only when I am Closing the servers, fist server closes properly but during second server closure LV crashes and connection to RT target loses.

**Closed** 2024-07-26 11:00 UTC
